-- MySQL Script generated by MySQL Workbench
-- Fri Jul 27 20:49:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `school` ;

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` DEFAULT CHARACTER SET utf8 ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`User_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`User_info` ;

CREATE TABLE IF NOT EXISTS `school`.`User_info` (
  `user_info_id` INT NOT NULL AUTO_INCREMENT,
  `real_name` VARCHAR(45) NULL COMMENT '真实姓名',
  `address` VARCHAR(45) NULL COMMENT '地址',
  `telephone` VARCHAR(11) NULL COMMENT '电话',
  `email` VARCHAR(45) NULL COMMENT '邮箱',
  `user_name` VARCHAR(45) NULL COMMENT '用户名',
  `user_password` VARCHAR(45) NULL COMMENT '密码',
  `reg_time` VARCHAR(45) NULL COMMENT '登录时间',
  PRIMARY KEY (`user_info_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`Student` ;

CREATE TABLE IF NOT EXISTS `school`.`Student` (
  `stu_id` VARCHAR(20) NOT NULL COMMENT '学生编号',
  `stu_college` VARCHAR(45) NOT NULL COMMENT '学院',
  `stu_major` VARCHAR(45) NOT NULL COMMENT '专业',
  `stu_grade` CHAR(4) NOT NULL COMMENT '年级',
  `User_user_info_id` INT NOT NULL,
  PRIMARY KEY (`stu_id`),
  INDEX `fk_Student_User1_idx` (`User_user_info_id` ASC),
  CONSTRAINT `fk_Student_User1`
    FOREIGN KEY (`User_user_info_id`)
    REFERENCES `school`.`User_info` (`user_info_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Admin_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`Admin_info` ;

CREATE TABLE IF NOT EXISTS `school`.`Admin_info` (
  `admin_id` INT NOT NULL AUTO_INCREMENT COMMENT '管理员编号',
  `admin_block_id` INT NOT NULL COMMENT '管理员版块编号1.动态信息发布2.网站运营管理3.信息展示4.用户信息管理5.在线交互',
  `User_user_info_id` INT NOT NULL,
  PRIMARY KEY (`admin_id`),
  INDEX `fk_Admin_User1_idx` (`User_user_info_id` ASC),
  CONSTRAINT `fk_Admin_User1`
    FOREIGN KEY (`User_user_info_id`)
    REFERENCES `school`.`User_info` (`user_info_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`Post` ;

CREATE TABLE IF NOT EXISTS `school`.`Post` (
  `post_id` INT NOT NULL AUTO_INCREMENT COMMENT '帖子编号',
  `post_content` VARCHAR(2000) NOT NULL COMMENT '帖子内容',
  `post_up_time` VARCHAR(45) NOT NULL COMMENT '发帖时间',
  `post_del_time` VARCHAR(45) NULL COMMENT '删帖时间',
  `Student_stu_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `fk_Post_Student1_idx` (`Student_stu_id` ASC),
  CONSTRAINT `fk_Post_Student1`
    FOREIGN KEY (`Student_stu_id`)
    REFERENCES `school`.`Student` (`stu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`Comments` ;

CREATE TABLE IF NOT EXISTS `school`.`Comments` (
  `comment_id` INT NOT NULL AUTO_INCREMENT COMMENT '评论编号',
  `comment_content` VARCHAR(45) NOT NULL COMMENT '评论内容',
  `comment_up_time` VARCHAR(45) NOT NULL COMMENT '评论时间',
  `comment_del_time` VARCHAR(45) NULL COMMENT '删评时间',
  `Student_stu_id` VARCHAR(20) NOT NULL,
  `Post_post_id` INT NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_Comments_Student1_idx` (`Student_stu_id` ASC),
  INDEX `fk_Comments_Post1_idx` (`Post_post_id` ASC),
  CONSTRAINT `fk_Comments_Student1`
    FOREIGN KEY (`Student_stu_id`)
    REFERENCES `school`.`Student` (`stu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Post1`
    FOREIGN KEY (`Post_post_id`)
    REFERENCES `school`.`Post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Reply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`Reply` ;

CREATE TABLE IF NOT EXISTS `school`.`Reply` (
  `reply_id` INT NOT NULL AUTO_INCREMENT COMMENT '回复编号',
  `reply_content` VARCHAR(45) NOT NULL COMMENT '回复内容',
  `reply_time` VARCHAR(45) NOT NULL COMMENT '评论时间',
  `Student_stu_id` VARCHAR(20) NOT NULL,
  `Comments_comment_id` INT NOT NULL,
  PRIMARY KEY (`reply_id`),
  INDEX `fk_Reply_Student1_idx` (`Student_stu_id` ASC),
  INDEX `fk_Reply_Comments1_idx` (`Comments_comment_id` ASC),
  CONSTRAINT `fk_Reply_Student1`
    FOREIGN KEY (`Student_stu_id`)
    REFERENCES `school`.`Student` (`stu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reply_Comments1`
    FOREIGN KEY (`Comments_comment_id`)
    REFERENCES `school`.`Comments` (`comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Log_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`Log_record` ;

CREATE TABLE IF NOT EXISTS `school`.`Log_record` (
  `log_id` INT NOT NULL AUTO_INCREMENT COMMENT '日志编号',
  `log_time` VARCHAR(45) NOT NULL COMMENT '日志时间',
  `operation_ip` VARCHAR(45) NOT NULL COMMENT '操作IP',
  `log_content` VARCHAR(100) NULL COMMENT '日志内容',
  PRIMARY KEY (`log_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Department_introduction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`Department_introduction` ;

CREATE TABLE IF NOT EXISTS `school`.`Department_introduction` (
  `department_id` INT NOT NULL AUTO_INCREMENT COMMENT '院系编号',
  `department_title` VARCHAR(45) NOT NULL COMMENT '院系名称',
  `department_update_time` VARCHAR(45) NOT NULL COMMENT '更新时间',
  `department_content` VARCHAR(2000) NOT NULL COMMENT '院系简介内容',
  `department_acess_number` INT NOT NULL DEFAULT 0 COMMENT '院系简介访问量',
  `Admin_admin_id` INT NOT NULL,
  PRIMARY KEY (`department_id`),
  INDEX `fk_Department_introduction_Admin1_idx` (`Admin_admin_id` ASC),
  CONSTRAINT `fk_Department_introduction_Admin1`
    FOREIGN KEY (`Admin_admin_id`)
    REFERENCES `school`.`Admin_info` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Professional_introduction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`Professional_introduction` ;

CREATE TABLE IF NOT EXISTS `school`.`Professional_introduction` (
  `professional_id` INT NOT NULL AUTO_INCREMENT COMMENT '专业编号',
  `professional_title` VARCHAR(45) NOT NULL COMMENT '专业名称',
  `professional_update_time` VARCHAR(45) NOT NULL COMMENT '专业介绍更新时间',
  `professional_content` VARCHAR(2000) NOT NULL COMMENT '专业介绍内容',
  `professional_acess_number` INT NOT NULL DEFAULT 0 COMMENT '专业介绍访问量',
  `Admin_admin_id` INT NOT NULL,
  `Department_introduction_department_id` INT NOT NULL,
  PRIMARY KEY (`professional_id`),
  INDEX `fk_Professional_introduction_Admin1_idx` (`Admin_admin_id` ASC),
  INDEX `fk_Professional_introduction_Department_introduction1_idx` (`Department_introduction_department_id` ASC),
  CONSTRAINT `fk_Professional_introduction_Admin1`
    FOREIGN KEY (`Admin_admin_id`)
    REFERENCES `school`.`Admin_info` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professional_introduction_Department_introduction1`
    FOREIGN KEY (`Department_introduction_department_id`)
    REFERENCES `school`.`Department_introduction` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`School_introduction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`School_introduction` ;

CREATE TABLE IF NOT EXISTS `school`.`School_introduction` (
  `school_id` INT NOT NULL AUTO_INCREMENT COMMENT '学校简介编号',
  `school_title` VARCHAR(45) NOT NULL COMMENT '学校简介标题',
  `school_update_time` VARCHAR(45) NOT NULL COMMENT '学校简介更新时间',
  `school_content` VARCHAR(2000) NOT NULL COMMENT '学校简介内容',
  `school_acess_number` INT NOT NULL DEFAULT 0 COMMENT '访问量',
  `Admin_admin_id` INT NOT NULL,
  PRIMARY KEY (`school_id`),
  INDEX `fk_School_introduction_Admin1_idx` (`Admin_admin_id` ASC),
  CONSTRAINT `fk_School_introduction_Admin1`
    FOREIGN KEY (`Admin_admin_id`)
    REFERENCES `school`.`Admin_info` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Admission_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`Admission_info` ;

CREATE TABLE IF NOT EXISTS `school`.`Admission_info` (
  `adm_info_id` INT NOT NULL AUTO_INCREMENT COMMENT '招生信息编号',
  `adm_info_title` VARCHAR(45) NOT NULL COMMENT '招生信息标题',
  `adm_info_content` VARCHAR(2000) NOT NULL COMMENT '招生信息内容',
  `adm_info_time` VARCHAR(45) NOT NULL COMMENT '发布时间',
  `adm_acess_number` INT NOT NULL DEFAULT 0 COMMENT '访问量',
  `Admin_admin_id` INT NOT NULL,
  PRIMARY KEY (`adm_info_id`),
  INDEX `fk_Admission_info_Admin1_idx` (`Admin_admin_id` ASC),
  CONSTRAINT `fk_Admission_info_Admin1`
    FOREIGN KEY (`Admin_admin_id`)
    REFERENCES `school`.`Admin_info` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Employ_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`Employ_info` ;

CREATE TABLE IF NOT EXISTS `school`.`Employ_info` (
  `emp_info_id` INT NOT NULL AUTO_INCREMENT COMMENT '就业信息编号',
  `emp_info_title` VARCHAR(45) NOT NULL COMMENT '就业信息标题',
  `emp_info_content` VARCHAR(2000) NOT NULL COMMENT '就业信息内容',
  `emp_info_time` VARCHAR(45) NOT NULL COMMENT '发布时间',
  `emp_acess_number` INT NOT NULL DEFAULT 0 COMMENT '访问量',
  `Admin_admin_id` INT NOT NULL,
  PRIMARY KEY (`emp_info_id`),
  INDEX `fk_Employ_info_Admin1_idx` (`Admin_admin_id` ASC),
  CONSTRAINT `fk_Employ_info_Admin1`
    FOREIGN KEY (`Admin_admin_id`)
    REFERENCES `school`.`Admin_info` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Notice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`Notice` ;

CREATE TABLE IF NOT EXISTS `school`.`Notice` (
  `notice_id` INT NOT NULL AUTO_INCREMENT COMMENT '公告编号',
  `notice_content` VARCHAR(2000) NOT NULL COMMENT '公告内容',
  `notice_time` VARCHAR(45) NOT NULL COMMENT '发布时间',
  `notice_acess_number` INT NOT NULL DEFAULT 0 COMMENT '访问量',
  `Admin_admin_id` INT NOT NULL,
  PRIMARY KEY (`notice_id`),
  INDEX `fk_Notice_Admin1_idx` (`Admin_admin_id` ASC),
  CONSTRAINT `fk_Notice_Admin1`
    FOREIGN KEY (`Admin_admin_id`)
    REFERENCES `school`.`Admin_info` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`News_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`News_type` ;

CREATE TABLE IF NOT EXISTS `school`.`News_type` (
  `type_id` INT NOT NULL AUTO_INCREMENT COMMENT '类别编号',
  `type_name` VARCHAR(45) NOT NULL COMMENT '类别名称',
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`Picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`Picture` ;

CREATE TABLE IF NOT EXISTS `school`.`Picture` (
  `picture_id` INT NOT NULL AUTO_INCREMENT COMMENT '图片编号',
  `picture_name` VARCHAR(45) NOT NULL COMMENT '图片名称',
  `picture_category` VARCHAR(45) NOT NULL COMMENT '文章分类',
  `acess_id` INT NOT NULL COMMENT '文章编号',
  PRIMARY KEY (`picture_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`File`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`File` ;

CREATE TABLE IF NOT EXISTS `school`.`File` (
  `file_id` INT NOT NULL AUTO_INCREMENT COMMENT '文件编号',
  `file_name` VARCHAR(45) NOT NULL COMMENT '文件名称',
  `file_article_cate` INT NOT NULL COMMENT '文章类别',
  `file_article_id` INT NOT NULL COMMENT '文章编号',
  PRIMARY KEY (`file_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`News`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school`.`News` ;

CREATE TABLE IF NOT EXISTS `school`.`News` (
  `news_id` INT NOT NULL AUTO_INCREMENT COMMENT '新闻编号',
  `news_title` VARCHAR(45) NOT NULL COMMENT '新闻标题',
  `news_content` VARCHAR(2000) NOT NULL COMMENT '新闻内容',
  `news_time` VARCHAR(45) NOT NULL COMMENT '发布时间',
  `news_acess_number` INT NOT NULL DEFAULT 0 COMMENT '访问量',
  `Admin_admin_id` INT NOT NULL,
  `News_type_type_id` INT NOT NULL,
  PRIMARY KEY (`news_id`),
  INDEX `fk_News_Admin1_idx` (`Admin_admin_id` ASC),
  INDEX `fk_News_News_type1_idx` (`News_type_type_id` ASC),
  CONSTRAINT `fk_News_Admin1`
    FOREIGN KEY (`Admin_admin_id`)
    REFERENCES `school`.`Admin_info` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_News_News_type1`
    FOREIGN KEY (`News_type_type_id`)
    REFERENCES `school`.`News_type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
